os:
  - linux
  - osx
  - windows
sudo: false
language: go
go_import_path: l7e.io/vanity
go:
  - 1.27.x
before_install:
  - >
    if [ $TRAVIS_GO_VERSION =~ ^1\.27 -a "$TRAVIS_OS_NAME" = 'linux' ]; then
      go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
    fi
  - go install github.com/mattn/goveralls@latest
script:
  - >
    if [ $TRAVIS_GO_VERSION =~ ^1\.27 -a "$TRAVIS_OS_NAME" = 'linux' ]; then
      $GOPATH/bin/golangci-lint run ;
    fi
  - $GOPATH/bin/goveralls -service=travis-ci -race -v
after_success:
  - bash <(curl -s https://codecov.io/bash)
