// Code generated by protoc-gen-go. DO NOT EDIT.
// source: entry.proto

package datastore

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Entry struct {
	ImportPath           string   `protobuf:"bytes,1,opt,name=importPath,proto3" json:"importPath,omitempty"`
	Vcs                  string   `protobuf:"bytes,2,opt,name=vcs,proto3" json:"vcs,omitempty"`
	VcsRoot              string   `protobuf:"bytes,3,opt,name=vcsRoot,proto3" json:"vcsRoot,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Entry) Reset()         { *m = Entry{} }
func (m *Entry) String() string { return proto.CompactTextString(m) }
func (*Entry) ProtoMessage()    {}
func (*Entry) Descriptor() ([]byte, []int) {
	return fileDescriptor_daa6c5b6c627940f, []int{0}
}

func (m *Entry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Entry.Unmarshal(m, b)
}
func (m *Entry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Entry.Marshal(b, m, deterministic)
}
func (m *Entry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Entry.Merge(m, src)
}
func (m *Entry) XXX_Size() int {
	return xxx_messageInfo_Entry.Size(m)
}
func (m *Entry) XXX_DiscardUnknown() {
	xxx_messageInfo_Entry.DiscardUnknown(m)
}

var xxx_messageInfo_Entry proto.InternalMessageInfo

func (m *Entry) GetImportPath() string {
	if m != nil {
		return m.ImportPath
	}
	return ""
}

func (m *Entry) GetVcs() string {
	if m != nil {
		return m.Vcs
	}
	return ""
}

func (m *Entry) GetVcsRoot() string {
	if m != nil {
		return m.VcsRoot
	}
	return ""
}

func init() {
	proto.RegisterType((*Entry)(nil), "livetribe.vanity.gcp.datastore.Entry")
}

func init() { proto.RegisterFile("entry.proto", fileDescriptor_daa6c5b6c627940f) }

var fileDescriptor_daa6c5b6c627940f = []byte{
	// 162 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4e, 0xcd, 0x2b, 0x29,
	0xaa, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x52, 0xca, 0xc9, 0x2c, 0x4b, 0x2d, 0x29, 0xca,
	0x4c, 0x4a, 0xd5, 0x4b, 0x2d, 0x4e, 0x2e, 0x2d, 0x49, 0xce, 0x48, 0xcd, 0xcf, 0xd3, 0x4b, 0x4f,
	0x2e, 0xd0, 0x4b, 0x49, 0x2c, 0x49, 0x2c, 0x2e, 0xc9, 0x2f, 0x4a, 0x55, 0x0a, 0xe6, 0x62, 0x75,
	0x05, 0x69, 0x11, 0x92, 0xe3, 0xe2, 0xca, 0xcc, 0x2d, 0xc8, 0x2f, 0x2a, 0x09, 0x48, 0x2c, 0xc9,
	0x90, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x42, 0x12, 0x11, 0x12, 0xe0, 0x62, 0x2e, 0x4b, 0x2e,
	0x96, 0x60, 0x02, 0x4b, 0x80, 0x98, 0x42, 0x12, 0x5c, 0xec, 0x65, 0xc9, 0xc5, 0x41, 0xf9, 0xf9,
	0x25, 0x12, 0xcc, 0x60, 0x51, 0x18, 0xd7, 0x49, 0x35, 0x4a, 0x39, 0xc7, 0x3c, 0x55, 0x2f, 0x33,
	0x5f, 0x1f, 0x61, 0xaf, 0x7e, 0x41, 0x76, 0xba, 0x7e, 0x7a, 0x72, 0x81, 0x3e, 0xdc, 0xee, 0x24,
	0x36, 0xb0, 0x33, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x14, 0x2c, 0xfa, 0x01, 0xb5, 0x00,
	0x00, 0x00,
}
